import React from 'react'

import { TimelineScroller } from './TimelineScroller'

export default {
  title: 'TimelineScroller',
  component: TimelineScroller,
}

const Template = (args) => <TimelineScroller {...args} />

export const Primary = Template.bind({})
Primary.args = {
  timelines: [
    {
      id: '1',
      name: 'Europa',
      time_entries: [
        {
          name: 'Inicio da Primeira Guerra Mundial',
          year: 1914,
          month: 7,
          day: 28,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Evento no começo do ano',
          year: 1914,
          month: 2,
          day: 28,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Evento no mesmo dia',
          year: 1914,
          month: 7,
          day: 28,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Evento sem dia',
          year: 1914,
          month: 7,
          day: null,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Evento sem dia 2',
          year: 1914,
          month: 6,
          day: null,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Evento sem dia 3',
          year: 1914,
          month: 7,
          day: null,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Evento sem mês',
          year: 1914,
          month: null,
          day: null,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Término da Primeira Guerra Mundial',
          year: 1918,
          month: 11,
          day: 11,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Inicio da Segunda Guerra Mundial',
          year: 1939,
          month: 9,
          day: 1,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Término da Primeira Guerra Mundial',
          year: 1945,
          month: 9,
          day: 2,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
        {
          name: 'Fundação da União Europeia',
          year: 1993,
          month: 11,
          day: 1,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '1',
        },
      ],
    },
    {
      id: '2',
      name: 'Brasil',
      time_entries: [
        {
          name: 'Independência do Brasil',
          year: 1822,
          month: 9,
          day: 7,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
        {
          name: 'Abolição do trabalho escravo',
          year: 1888,
          month: 5,
          day: 13,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
        {
          name: 'Morte de Getúlio Vargas',
          year: 1954,
          month: 8,
          day: 24,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
        {
          name: 'Fundação de Brasília',
          year: 1960,
          month: 4,
          day: 21,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
        {
          name: 'Evento teste',
          year: 1960,
          month: 1,
          day: 1,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
        {
          name: 'Evento teste 2',
          year: 1960,
          month: 5,
          day: 1,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
        {
          name: 'Evento teste 3',
          year: 1960,
          month: 5,
          day: 2,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
        {
          name: 'Evento teste 4',
          year: 1960,
          month: 6,
          day: 1,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
        {
          name: 'Evento teste 5',
          year: 1960,
          month: 6,
          day: 1,
          annual_importance: true,
          monthly_importance: false,
          timeline_id: '2',
        },
      ],
    },
  ],
}
